# Generated by Django 4.0.1 on 2022-01-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Image', models.CharField(max_length=255)),
                ('HeaderImage', models.CharField(max_length=255)),
                ('Introduction', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=1000)),
                ('LastMod', models.DateField()),
                ('Language', models.CharField(max_length=255)),
                ('KeyWords', models.CharField(max_length=1000)),
                ('State', models.IntegerField()),
                ('NumVisit', models.IntegerField()),
                ('IdTheme', models.IntegerField()),
                ('IdUser', models.IntegerField()),
                ('IdHost', models.IntegerField()),
            ],
        ),
    ]
